export type DomainErrorCode =
  | "VENTURE_NAME_REQUIRED"
  | "VENTURE_OWNER_REQUIRED"
  | "VENTURE_INVALID_STATUS"
  | "VENTURE_INVALID_TRANSITION"
  | "VENTURE_ARCHIVE_BLOCKED"
  | "INITIATIVE_VENTURE_REQUIRED"
  | "INITIATIVE_NAME_REQUIRED"
  | "INITIATIVE_INVALID_STATUS"
  | "INITIATIVE_INVALID_CLOSURE_OUTCOME"
  | "INITIATIVE_BUDGET_INCOMPLETE"
  | "INITIATIVE_BUDGET_INVALID"
  | "INITIATIVE_INVALID_TRANSITION"
  | "INITIATIVE_ATTRIBUTION_BLOCKED"
  | "INITIATIVE_CLOSE_LESSON_REQUIRED"
  | "DECISION_TITLE_REQUIRED"
  | "DECISION_OUTCOME_REQUIRED"
  | "DECISION_INVALID_STATUS"
  | "DECISION_INVALID_TYPE"
  | "DECISION_SCOPE_REQUIRED"
  | "DECISION_VENTURE_NOT_FOUND"
  | "DECISION_INITIATIVE_NOT_FOUND"
  | "DECISION_SCOPE_MISMATCH"
  | "DECISION_INVALID_TRANSITION"
  | "DECISION_DELETE_FORBIDDEN"
  | "ATTRIBUTION_INITIATIVE_NOT_ELIGIBLE"
  | "ATTRIBUTION_ALLOCATION_INVALID"
  | "ATTRIBUTION_SPLIT_EXCEEDS_MAX"
  | "ATTRIBUTION_DUPLICATE"
  | "ATTRIBUTION_INVALID_STATUS"
  | "ATTRIBUTION_DELETE_FORBIDDEN"
  | "ATTRIBUTION_SIDECAR_VIOLATION"
  | "KPI_KEY_UNKNOWN";

export interface DomainError {
  code: DomainErrorCode;
  message: string;
}
