export type LearningDomainErrorCode =
  | "LEARNING_ILLEGAL_TRANSITION"
  | "LEARNING_PROVENANCE_INCOMPLETE"
  | "LEARNING_PROVENANCE_INVALID"
  | "LEARNING_COMPANY_MISMATCH"
  | "LEARNING_ENGAGEMENT_MISMATCH"
  | "LEARNING_GATE_BLOCKED"
  | "LEARNING_INVALID_CANDIDATE_TYPE"
  | "LEARNING_INVALID_ACTOR"
  | "LEARNING_AI_ACTOR_FORBIDDEN"
  | "LEARNING_HUMAN_APPROVAL_REQUIRED"
  | "LEARNING_ALREADY_TERMINAL"
  | "LEARNING_ALREADY_PROMOTED"
  | "LEARNING_NOT_APPROVED"
  | "LEARNING_NOT_PROMOTION_ELIGIBLE"
  | "LEARNING_VERSION_CONFLICT"
  | "LEARNING_INVALID_INPUT"
  | "LEARNING_RUN_ILLEGAL_TRANSITION";

export interface LearningDomainError {
  code: LearningDomainErrorCode;
  message: string;
}
