import React, { useState } from "react";
import { useAuth } from "../hooks/useAuth";
import { db } from "../services/firebase";
import {
  generateInvoiceAuthCode,
  normalizeVerificationCode,
} from "../utils/invoiceAuthCode";
import type { Invoice } from "../types";

const verifyByLegacyScan = async (
  companyId: string,
  code: string,
): Promise<Invoice | null> => {
  const invoicesSnapshot = await db
    .collection("invoices")
    .where("companyId", "==", companyId)
    .get();

  for (const doc of invoicesSnapshot.docs) {
    const invoice = { id: doc.id, ...doc.data() } as Invoice;
    const expectedCode = generateInvoiceAuthCode(
      invoice.id,
      invoice.invoiceNumber,
      companyId,
      invoice.createdById || "unknown",
    );
    if (expectedCode === code) {
      return invoice;
    }
  }
  return null;
};

const InvoiceVerificationSection: React.FC = () => {
  const { user, userProfile } = useAuth();
  const [verificationCode, setVerificationCode] = useState("");
  const [verificationResult, setVerificationResult] = useState<{
    success: boolean;
    message: string;
    invoiceData?: any;
  } | null>(null);
  const [isVerifying, setIsVerifying] = useState(false);

  const verifyInvoiceCode = async () => {
    if (!verificationCode.trim()) {
      setVerificationResult({
        success: false,
        message: "Please enter an authentication code to verify.",
      });
      return;
    }

    setIsVerifying(true);
    setVerificationResult(null);

    try {
      const companyId = userProfile?.isOwner ? user?.uid : userProfile?.companyId;

      if (!companyId) {
        setVerificationResult({
          success: false,
          message: "Unable to verify: Company information not found.",
        });
        return;
      }

      const code = normalizeVerificationCode(verificationCode);

      let foundInvoice: Invoice | null = null;

      try {
        const indexed = await db
          .collection("invoices")
          .where("companyId", "==", companyId)
          .where("authVerificationCode", "==", code)
          .limit(1)
          .get();

        if (!indexed.empty) {
          const doc = indexed.docs[0];
          foundInvoice = { id: doc.id, ...doc.data() } as Invoice;
        }
      } catch (err: any) {
        // Missing composite index or rules: fall back to legacy scan
        if (err?.code === "failed-precondition") {
          console.warn(
            "Invoice verification: add Firestore index on invoices (companyId + authVerificationCode), using legacy scan.",
          );
        }
      }

      if (!foundInvoice) {
        foundInvoice = await verifyByLegacyScan(companyId, code);
      }

      if (foundInvoice) {
        let creatorName = "Unknown User";
        if (foundInvoice.createdById) {
          try {
            const creatorDoc = await db
              .collection("users")
              .doc(foundInvoice.createdById)
              .get();
            if (creatorDoc.exists) {
              const creatorData = creatorDoc.data();
              creatorName =
                creatorData?.displayName ||
                creatorData?.companyName ||
                creatorData?.email ||
                "Unknown User";
            }
          } catch (error) {
            console.error("Error fetching creator info:", error);
          }
        }

        setVerificationResult({
          success: true,
          message: "✅ Invoice is AUTHENTIC and was generated by your system.",
          invoiceData: {
            invoiceNumber: foundInvoice.invoiceNumber,
            customerName: foundInvoice.customerName,
            total: foundInvoice.total,
            status: foundInvoice.status,
            issueDate:
              foundInvoice.issueDate?.toDate?.()?.toLocaleDateString() || "N/A",
            createdBy: creatorName,
            currency: foundInvoice.bankAccountCurrency || "USD",
          },
        });
      } else {
        setVerificationResult({
          success: false,
          message:
            "❌ Invalid authentication code. This invoice was NOT generated by your system or the code is incorrect.",
        });
      }
    } catch (error) {
      console.error("Error verifying invoice:", error);
      setVerificationResult({
        success: false,
        message: "Error occurred while verifying the invoice. Please try again.",
      });
    } finally {
      setIsVerifying(false);
    }
  };

  const formatCurrency = (amount: number, currencyCode: string = "USD") => {
    const symbols: { [key: string]: string } = {
      USD: "$",
      EUR: "€",
      GBP: "£",
      PKR: "₨",
    };
    const symbol = symbols[currencyCode] || currencyCode;
    return `${symbol}${amount?.toFixed(2) || "0.00"}`;
  };

  return (
    <div>
      <div className="flex justify-between items-center mb-4">
        <h2 className="text-xl font-semibold text-gray-700 dark:text-white">
          Invoice Authentication Verification
        </h2>
        <div className="flex items-center text-sm text-gray-500 dark:text-gray-400">
          <svg
            className="w-4 h-4 mr-1"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={2}
              d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"
            />
          </svg>
          Verify PDF authenticity
        </div>
      </div>

      <div className="bg-blue-50 dark:bg-blue-900/20 p-4 rounded-lg mb-4">
        <p className="text-sm text-blue-800 dark:text-blue-200 mb-2">
          <strong>How to verify:</strong> Look for the authentication code at the
          bottom-right corner of any invoice PDF generated by your system. Enter
          that code below to verify if the invoice is authentic.
        </p>
        <p className="text-xs text-blue-600 dark:text-blue-300">
          Format: ABC-123-456789 (Company-Invoice-Hash)
        </p>
      </div>

      <div className="space-y-4">
        <div>
          <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
            Invoice Authentication Code
          </label>
          <div className="flex space-x-3">
            <input
              type="text"
              value={verificationCode}
              onChange={(e) => setVerificationCode(e.target.value.toUpperCase())}
              placeholder="Enter code (e.g., ABC-123-456789)"
              className="flex-1 p-3 border border-gray-300 rounded-md shadow-sm dark:bg-gray-700 dark:border-gray-600 dark:text-white font-mono"
              disabled={isVerifying}
            />
            <button
              onClick={verifyInvoiceCode}
              disabled={isVerifying || !verificationCode.trim()}
              className="px-6 py-3 bg-blue-600 text-white rounded-md hover:bg-blue-700 disabled:bg-gray-400 disabled:cursor-not-allowed font-medium"
            >
              {isVerifying ? "Verifying..." : "Verify"}
            </button>
          </div>
        </div>

        {verificationResult && (
          <div
            className={`p-4 rounded-lg border-l-4 ${
              verificationResult.success
                ? "bg-green-50 border-green-400 dark:bg-green-900/20 dark:border-green-500"
                : "bg-red-50 border-red-400 dark:bg-red-900/20 dark:border-red-500"
            }`}
          >
            <div
              className={`font-medium ${
                verificationResult.success
                  ? "text-green-800 dark:text-green-200"
                  : "text-red-800 dark:text-red-200"
              }`}
            >
              {verificationResult.message}
            </div>

            {verificationResult.success && verificationResult.invoiceData && (
              <div className="mt-3 space-y-2">
                <div className="text-sm text-green-700 dark:text-green-300">
                  <strong>Invoice Details:</strong>
                </div>
                <div className="grid grid-cols-2 md:grid-cols-3 gap-4 text-sm">
                  <div>
                    <span className="text-gray-600 dark:text-gray-400">
                      Invoice #:
                    </span>
                    <div className="font-medium text-gray-900 dark:text-white">
                      {verificationResult.invoiceData.invoiceNumber}
                    </div>
                  </div>
                  <div>
                    <span className="text-gray-600 dark:text-gray-400">
                      Customer:
                    </span>
                    <div className="font-medium text-gray-900 dark:text-white">
                      {verificationResult.invoiceData.customerName}
                    </div>
                  </div>
                  <div>
                    <span className="text-gray-600 dark:text-gray-400">
                      Amount:
                    </span>
                    <div className="font-medium text-gray-900 dark:text-white">
                      {formatCurrency(
                        verificationResult.invoiceData.total,
                        verificationResult.invoiceData.currency,
                      )}
                    </div>
                  </div>
                  <div>
                    <span className="text-gray-600 dark:text-gray-400">
                      Status:
                    </span>
                    <div className="font-medium text-gray-900 dark:text-white">
                      <span
                        className={`px-2 py-1 rounded-full text-xs ${
                          verificationResult.invoiceData.status === "paid"
                            ? "bg-green-100 text-green-800 dark:bg-green-800 dark:text-green-100"
                            : verificationResult.invoiceData.status === "sent"
                              ? "bg-blue-100 text-blue-800 dark:bg-blue-800 dark:text-blue-100"
                              : "bg-gray-100 text-gray-800 dark:bg-gray-700 dark:text-gray-300"
                        }`}
                      >
                        {verificationResult.invoiceData.status}
                      </span>
                    </div>
                  </div>
                  <div>
                    <span className="text-gray-600 dark:text-gray-400">
                      Issue Date:
                    </span>
                    <div className="font-medium text-gray-900 dark:text-white">
                      {verificationResult.invoiceData.issueDate}
                    </div>
                  </div>
                  <div>
                    <span className="text-gray-600 dark:text-gray-400">
                      Created By:
                    </span>
                    <div className="font-medium text-gray-900 dark:text-white">
                      {verificationResult.invoiceData.createdBy}
                    </div>
                  </div>
                </div>
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
};

export default InvoiceVerificationSection;
