/**
 * Lead acquisition / attribution sources for the new-lead form (searchable dropdown).
 * Sorted A→Z; use SOURCE_CUSTOM_VALUE + custom field for anything not listed.
 */
const LEAD_SOURCE_RAW: string[] = [
  "Affiliate / partner program",
  "AngelList / Wellfound",
  "AppSumo",
  "Billboard / outdoor ad",
  "Bing Ads",
  "Blog / SEO content",
  "Capterra",
  "Clutch",
  "Cold call",
  "Cold email / outreach",
  "Community / forum",
  "Competitor mention",
  "Conference",
  "Craigslist / classifieds",
  "Discord",
  "Direct mail",
  "Email campaign",
  "Employee referral",
  "Event / trade show",
  "Existing customer (repeat)",
  "Facebook",
  "Facebook Ads / Meta Ads",
  "Fiverr",
  "Freelancer.com",
  "G2",
  "Glassdoor",
  "Google Ads",
  "Google Business Profile",
  "Google organic search",
  "Gumroad",
  "Instagram",
  "Instagram Ads",
  "Influencer / creator",
  "Investor / advisor intro",
  "Job board",
  "LinkedIn",
  "LinkedIn Ads",
  "Magazine / print",
  "Marketplace (other)",
  "Newsletter",
  "Newspaper ad",
  "OLX / local classifieds",
  "Organic search (other)",
  "Partner / reseller",
  "Pinterest",
  "Podcast",
  "Product Hunt",
  "Quora",
  "Radio",
  "Reddit",
  "Referral — friend / colleague",
  "Shopify App Store",
  "Slack community",
  "SMS / text campaign",
  "Telegram",
  "TikTok",
  "TikTok Ads",
  "Trade publication",
  "Trustpilot",
  "TV commercial",
  "Twitter / X",
  "University / career fair",
  "Upwork",
  "Walk-in",
  "Webinar",
  "Website",
  "Website — chat widget",
  "Website — contact form",
  "WhatsApp Business",
  "Word of mouth",
  "Yellow Pages",
  "Yelp",
  "YouTube",
  "YouTube Ads",
];

export const LEAD_SOURCE_PRESETS: readonly string[] = [...LEAD_SOURCE_RAW].sort((a, b) =>
  a.localeCompare(b, undefined, { sensitivity: "base" }),
);
