import { AGENCY_TYPE } from "../../constants/agencyType";
import { DELIVERY_STATE } from "../../constants/deliveryState";
import type { PlaybookEntryDetailDto } from "./dto/PlaybookDto";

const SEED: readonly PlaybookEntryDetailDto[] = [
  {
    entryId: "pb-agency-core",
    title: "Agency Delivery Playbook",
    entryType: "agency_playbook",
    agencyTypes: [AGENCY_TYPE.WEB, AGENCY_TYPE.SAAS, AGENCY_TYPE.AI, AGENCY_TYPE.MOBILE],
    version: "1.2.0",
    summary: "Founder workflow from intake through retrospective — gates before Cursor execution.",
    tags: ["methodology", "lifecycle", "gates"],
    body:
      "Delivery engagements advance through factual lifecycle states. Each gate requires human approval before the next artifact class is generated. AI assists drafting; founders approve.",
    checklist: [
      "Confirm ERP customer exists before intake",
      "Approve requirements before reuse scan",
      "Approve prompt pack before Cursor session",
      "Pass evaluation before QA handoff",
    ],
    knowledgeReferences: [{ patternId: "kp-sidecar-law", title: "Sidecar law reference pattern" }],
    relatedTemplates: [{ entryId: "tpl-web-intake", title: "Web Intake Template" }],
  },
  {
    entryId: "tpl-web-intake",
    title: "Web Intake Template",
    entryType: "template",
    lifecyclePhase: DELIVERY_STATE.INTAKE,
    agencyTypes: [AGENCY_TYPE.WEB],
    version: "2.0.0",
    summary: "Standard intake checklist for web delivery engagements.",
    tags: ["intake", "web", "checklist"],
    body: "Use during intake to confirm scope boundaries, ERP customer linkage, and agency type profile.",
    checklist: ["Link ERP customer", "Assign delivery lead", "Capture scope summary"],
    knowledgeReferences: [],
    relatedTemplates: [{ entryId: "pb-agency-core", title: "Agency Delivery Playbook" }],
  },
  {
    entryId: "rub-eval-first-pass",
    title: "First-Pass Evaluation Rubric",
    entryType: "rubric",
    lifecyclePhase: DELIVERY_STATE.EVALUATING,
    agencyTypes: [AGENCY_TYPE.WEB, AGENCY_TYPE.SAAS, AGENCY_TYPE.AI],
    version: "1.0.0",
    summary: "Pass/fail criteria for Cursor session output before QA.",
    tags: ["evaluation", "quality", "rubrics"],
    body: "Score against acceptance checks defined in the approved prompt pack. Failures require iteration before QA.",
    checklist: ["Session ID recorded", "Artifacts match pack version", "Acceptance checks explicit"],
    knowledgeReferences: [{ patternId: "kp-eval-first-pass", title: "Evaluation first-pass criteria" }],
    relatedTemplates: [{ entryId: "eval-template-standard", title: "Standard Evaluation Template" }],
  },
  {
    entryId: "pt-reuse-block",
    title: "Reuse Block Prompt Template",
    entryType: "prompt_template",
    lifecyclePhase: DELIVERY_STATE.PLANNING,
    agencyTypes: [AGENCY_TYPE.WEB, AGENCY_TYPE.SAAS],
    version: "1.1.0",
    summary: "Prompt artifact section listing approved registry modules for Cursor.",
    tags: ["prompts", "reuse", "cursor"],
    body: "Insert after constraints section. List module IDs with adaptation notes — never one-click install.",
    checklist: ["Module IDs from reuse assessment", "Net-new justification documented"],
    knowledgeReferences: [{ patternId: "kp-prompt-structure", title: "Prompt pack structure" }],
    relatedTemplates: [],
  },
  {
    entryId: "qs-form-a11y",
    title: "Form Accessibility Quality Standard",
    entryType: "quality_standard",
    lifecyclePhase: DELIVERY_STATE.BUILDING,
    agencyTypes: [AGENCY_TYPE.WEB, AGENCY_TYPE.SAAS],
    version: "1.0.0",
    summary: "Minimum accessibility bar for form-heavy deliverables.",
    tags: ["quality", "a11y", "forms"],
    body: "All inputs labeled, errors associated with fields, keyboard navigable approval flows.",
    checklist: ["htmlFor on labels", "aria-invalid on errors", "Focus order verified"],
    knowledgeReferences: [{ patternId: "kp-form-a11y", title: "Form accessibility checklist" }],
    relatedTemplates: [],
  },
  {
    entryId: "eval-template-standard",
    title: "Standard Evaluation Template",
    entryType: "evaluation_template",
    lifecyclePhase: DELIVERY_STATE.EVALUATING,
    agencyTypes: [AGENCY_TYPE.WEB, AGENCY_TYPE.AI, AGENCY_TYPE.SAAS],
    version: "1.0.0",
    summary: "Template for recording evaluation ID, session link, and pass/fail outcome.",
    tags: ["evaluation", "template"],
    body: "Bind evaluation to Cursor session and prompt pack version. Store evidence links only — no code copies.",
    checklist: ["Evaluation ID assigned", "Session referenced", "Rubric applied"],
    knowledgeReferences: [{ patternId: "kp-eval-first-pass", title: "Evaluation first-pass criteria" }],
    relatedTemplates: [{ entryId: "rub-eval-first-pass", title: "First-Pass Evaluation Rubric" }],
  },
  {
    entryId: "bp-gate-order",
    title: "Gate Order Best Practice",
    entryType: "best_practice",
    lifecyclePhase: DELIVERY_STATE.PLANNING,
    agencyTypes: [AGENCY_TYPE.WEB, AGENCY_TYPE.SAAS, AGENCY_TYPE.AI, AGENCY_TYPE.MOBILE],
    version: "1.0.0",
    summary: "Never skip requirements → reuse → prompts → cursor → evaluation sequence.",
    tags: ["gates", "workflow"],
    body: "Founder workflow tabs enforce sequential gates. Queue screens navigate to tabs — no inline approve.",
    checklist: ["Requirements approved", "Reuse recorded", "Prompt pack approved"],
    knowledgeReferences: [{ patternId: "kp-sidecar-law", title: "Sidecar law reference pattern" }],
    relatedTemplates: [{ entryId: "pb-agency-core", title: "Agency Delivery Playbook" }],
  },
  {
    entryId: "ds-handoff-checklist",
    title: "QA Handoff Delivery Standard",
    entryType: "delivery_standard",
    lifecyclePhase: DELIVERY_STATE.DELIVERING,
    agencyTypes: [AGENCY_TYPE.WEB, AGENCY_TYPE.SAAS],
    version: "1.0.0",
    summary: "Read-only checklist before client handoff — not task tracking.",
    tags: ["handoff", "qa"],
    body: "Confirm evaluation passed, QA complete, and retrospective scheduled before closed state.",
    checklist: ["Evaluation passed", "QA sign-off", "Retrospective scheduled"],
    knowledgeReferences: [],
    relatedTemplates: [],
  },
  {
    entryId: "kr-auth-ref",
    title: "Auth Patterns Knowledge Reference",
    entryType: "knowledge_reference",
    lifecyclePhase: DELIVERY_STATE.BUILDING,
    agencyTypes: [AGENCY_TYPE.WEB, AGENCY_TYPE.MOBILE],
    version: "1.0.0",
    summary: "Links playbook phases to canonical auth knowledge patterns.",
    tags: ["knowledge", "auth", "security"],
    body: "Reference kp-auth-gates when drafting security-related prompt constraints.",
    checklist: ["Pattern ID cited in prompt pack", "Module registry cross-check"],
    knowledgeReferences: [
      { patternId: "kp-auth-gates", title: "Auth gate sequencing" },
      { patternId: "kp-sidecar-law", title: "Sidecar law reference pattern" },
    ],
    relatedTemplates: [{ entryId: "pt-reuse-block", title: "Reuse Block Prompt Template" }],
  },
];

export function getPlaybookSeedCatalog(): readonly PlaybookEntryDetailDto[] {
  return SEED;
}

export function toPlaybookListItem(detail: PlaybookEntryDetailDto) {
  const {
    body: _body,
    checklist: _checklist,
    knowledgeReferences: _knowledgeReferences,
    relatedTemplates: _relatedTemplates,
    ...listItem
  } = detail;
  return listItem;
}
