/** Shared catalog search minimum — docs/aos-frontend-architecture/34_PERFORMANCE_GUIDELINES.md */
export const AOS_CATALOG_SEARCH_MIN_CHARS = 2;

export const REGISTRY_SEARCH_MIN_CHARS = AOS_CATALOG_SEARCH_MIN_CHARS;
export const KNOWLEDGE_SEARCH_MIN_CHARS = AOS_CATALOG_SEARCH_MIN_CHARS;
export const PLAYBOOK_SEARCH_MIN_CHARS = AOS_CATALOG_SEARCH_MIN_CHARS;
